### ISSUE TITLE
Make a plan for the next major release

### ISSUE THREAD

**Issue by rchl** [nuxt-modules/i18n#1198]
This issue is for tracking the progress of creating a new major release.
The major release should remove deprecated settings and clean up some existing settings.

- [x] Remove deprecated option `seo` (#1232)
- [x] Remove deprecated option `beforeLanguageSwitch` (#1200)
- [x] Remove deprecated API `$nuxtI18nSeo` (#1207)
- [x] Remove deprecated `NuxtVueI18n` type namespace (#1206)
- [x] Combine `detectBrowserLanguage.onlyOnNoPrefix` and `detectBrowserLanguage.onlyOnRoot` (#1210)
- [x] Remove vuex syncLocale & vuex syncMessages (#1240)
- [x] Change the `addDirAttribute` default to `false` (#1239)
- [x] Enable `detectBrowserLanguage.onlyOnRoot` by default (#1244)
- [x] Write migration guide and rename to `@nuxtjs/i18n` (#1247)
- [x] handle #800 (#1250)

**Comment by divine** [comment]
@rchl can I start the removal process separated by PR?

I think this might easy to pick up for me 😃 

Thanks!

**Comment by rchl** [comment]
Should be fine. I've created a `next` branch to create PRs against.

**Comment by divine** [comment]
We are almost at it finally!

The real question is as the new version will contain breaking changes then we might as well bump Vue I18n to v9 because of the soonish release of nuxt 3?

Thank you so much for your help @rchl!

**Comment by rchl** [comment]
Good idea, that sounds like something worth investigating.

**Comment by divine** [comment]
> Nuxt3 is ready to be released, in three stages.
> July 2021 Private beta for Vue core team, Nuxt module authors and partners.

@Atinux @pi0 @danielroe maybe some kind of access could be provided at least to @rchl to see what can be done?

Thanks!

**Comment by divine** [comment]
@rchl just a minor question that I wanted to ask.

Why `addDirAttribute` is by default: `true`?

Basically, it's adding an extra dir attribute, I don't think that more than %98 of nuxt sites need that `rtl` support?

Thanks!

**Comment by rchl** [comment]
I don't think there is very good reason for setting it by default. Not setting it should result in the same behavior if nothing related to direction was customized. But then it's very small and simple attribute so there is not really any downsides to setting it, IMO.

**Comment by divine** [comment]
> I don't think there is very good reason for setting it by default. Not seeing it should result in the same behavior if nothing related to direction was customized. But then it's very small and simple attribute so there is not really any downsides to setting it, IMO.

I have just checked it up, none of the top million of sites has that attribute by default so disabling it as well is a way to go.

The reason why I thought about it is that not everyone would be needed extra unneeded attribute which they'll be disabling afterward.

Just imagine to disable `dir="ltr"` (9 chars) you need to write `addDirAttribute: false` (22 chars)...

Thanks!

**Comment by rchl** [comment]
In https://github.com/nuxt-community/i18n-module/pull/1023 the initial code did:

>  if the dir property is defined it will be used in the html's dir attribute, if not, or the locales form is an array of codes, the dir property will be set to undefined and the attribute will not be added.

and in the later comment the author suggested:

> also, i'm thinking about adding a `defaultDirection` option in the module options, maybe with default value `auto` or `ltr` to be used when the dir property is not specified for any locale, or in case if someone wants to use `rtl` for multi-lang or dialect and `en` for specific one, then defaultDirection would help not specifying the dir in each locale, do you agree?

so the latter suggestion was applied.

But I'm not sure I fully understand that later suggestion. I think if the default would be undefined then it would still get removed if locale doesn't specify `dir: 'rtl'`.

So I think I'm fine with changing the default to `undefined` if we determine that it won't cause issues in any case.

@iifawzi Maybe you can clarify your old comment here.

**Comment by iifawzi** [comment]
Hello, it's been a while :') 

> But I'm not sure I fully understand that later suggestion. I think if the default would be undefined then it would still get removed if locale doesn't specify dir: 'rtl'.

Exactly, setting the default value of the constant `defaultDirection` to `undefined` would be enough for the property to be removed, but I would prefer changing `addDirAttribute` to `false` instead. 
https://github.com/nuxt-community/i18n-module/blob/9fcebdafd38f6ba8c6b052291ee159a742503c83/src/templates/head-meta.js#L9

if we set the default to `undefined`, and someone decided to use this feature and he wants his default `dir` to be `ltr`, he would need then to set `defaultDirection` to `ltr`, which's an additional step for the user - except if his default is `rtl` - I think keeping the default `ltr` and changing `addDirAttribute` to `false` would be more accurate for better user experience, IMHO.

Anyway, Both ways shouldn't cause any issues in any cases.

**Comment by rchl** [comment]
Sounds good to change the `addDirAttribute` default to `false` then.

**Comment by divine** [comment]
Hello,

@rchl the only thing I'd like to ask what will happen when `@nuxtjs/i18n` will reach version 6. Will be there any conflicts with the previous releases?

Thanks!

**Comment by rchl** [comment]
I can't think of any. Why do you think there might be?
Those will be a two separate packages with different names so I don't see how there would be any conflicts.

**Comment by divine** [comment]
> I can't think of any. Why do you think there might be?
> Those will be a two separate packages with different names so I don't see how there would be any conflicts.

I meant Github releases which doesn't allow creation of the same version so it might create a problem in this repository, not npm related.

Thanks!

**Comment by rchl** [comment]
It's a good point actually. Also it would be confusing to see releases in non-chronological order.

A separate repo might be the best idea...

**Comment by rchl** [comment]
Or as @pi0 suggested, change the name and release as v7.0.0.

**Comment by divine** [comment]
> A separate repo might be the best idea...

This is the only possible solution I think as it will preserve:
- Old documentation. 
- Old issues and possible solutions.

The new module is a major release which changed a lot and I'm sure a lot of questions will be made regarding old behavior which  changed a lot.

Renaming of this repository was a bit early I think. Anyways, it's up to you decide what would be the best.

Also, why you are not still a member of this repository as you are the only one who keeps this library maintained...so sad...

Thanks!

**Comment by rchl** [comment]
For documentation my plan is to have the documentation for the legacy (v6) version on a separate URL and then the new documentation will have a note of sort that says that "you are looking at the documentation for v7 and if you are looking for the old one click here".

So  with that in mind, I think keeping same repo will work. I'll create new issue to handle this.

> Also, why you are not still a member of this repository as you are the only one who keeps this library maintained...so sad...

I'm the admin of this repo. The only thing I don't have access to is organization-wide apps like netlify deploys configuration.

**Comment by divine** [comment]
> For documentation my plan is to have the documentation for the legacy (v6) version on a separate URL and then the new documentation will have a note of sort that says that "you are looking at the documentation for v7 and if you are looking for the old one click here".
> 
> So with that in mind, I think keeping same repo will work. I'll create new issue to handle this.


This sounds pretty good but maybe just add a link to the Github would be enough I have seen that mostly - not user friendly but less work I would say.

Let me know if I could help, maybe migrate to docus as well which will be released soon?

Thanks!

**Comment by rchl** [comment]
I think converting documentation to docus before its release is a waste of time. It was supposed to be released months (?) ago and it wasn't and probably a lot has changed since then.

(Note: I will probably have very little time, if any, to work on this this weekend)

**Comment by pi0** [comment]
Docus is getting much more stable but pending for nuxt3 to be public. In the meantime maybe @Tahul if you have some time can helping on docs migration? :)

**Comment by rchl** [comment]
There is an old PR at https://github.com/nuxt-community/i18n-module/pull/1034 but there was a serious issue with docus at that time at least.

**Comment by divine** [comment]
> There is an old PR at #1034 but there was a serious issue with docus at that time at least.

Not only that. I was able to use one of the versions when template was published which then started to fail due to unknown breaking changes?!

I might take care docus migration when it be publicly available and as you said it's not urgent. We did everything to release new major release.

Thanks!

**Comment by rchl** [comment]
All done!
