### ISSUE TITLE
Roadmap for v9

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#3002]
### Discussed in https://github.com/nuxt-modules/i18n/discussions/2814

<div type='discussions-op-text'>

<sup>Originally posted by **BobbieGoede** February 20, 2024</sup>
> [!NOTE]  
> This list is incomplete and a work in progress, feel free to suggest features, topics or issues that you think should be included in v9.

There's still plenty of issues open for v8 and we'll continue to work on fixing those, this roadmap is simply to plan and discuss changes that would be breaking. There is currently no estimate or deadline for the next major version, you don't have to worry about migrating (again) anytime soon.

### Features
- [x] support vue-i18n v10
- [x] support nuxt 4 

### Bug Fixes
- [x] support `v-t` fully SSR 

### Breaking changes
- [x] https://github.com/nuxt-modules/i18n/pull/2801
- [x] Rename locales property `iso` to `language`
  - [x] Add alias as described in https://github.com/nuxt-modules/i18n/issues/2449#issuecomment-1740517847 to allow for easier transition
- [x] https://github.com/nuxt-modules/i18n/issues/2712
- [x] Restructure `runtimeConfig` keys
  - [x] Rename `locales` to `domainLocales` and `configLocales` to `locales` (https://github.com/nuxt-modules/i18n/pull/2828#discussion_r1513740467)
- [x] enable jit compilation as default (remove `jit` option) https://i18n.nuxtjs.org/docs/options/compilation#jit
- [x] Fix prefixed injected functions (https://github.com/nuxt-modules/i18n/issues/2168), this is a breaking change as currently the unprefixed inject functions do work but should not and prefixed functions don't.
- [x] Changing/aligning `useLocaleHead` and `useSetI18nParams` argument defaults

### Postponed
- [ ] Change route localization to omit parent from path in `defineI18nRoute` as described in https://github.com/nuxt-modules/i18n/pull/2743#issue-2108024664
  - This can be a non-breaking change if we implement this using relative paths as described in https://github.com/nuxt/nuxt/discussions/28826#localizing-routes
- [ ] https://github.com/nuxt-modules/i18n/issues/1985
  - This is a non trivial change, options used at build time should be taken into consideration, as well as layer support and more. Feel free to open issues, PRs or open a discussion to brainstorm solutions.

### Considering
* Change `locales` configuration
  * Remove `file`, only accepting `files` array instead, simplifies options merging.

</div>

**Comment by MinecraftStorage1** [comment]
Can you also add support for custom routing? So that routes defined in router.options.js file are also prefixed. Many big websites prefer custom routing because of the greater flexibility it offers. But as I18n doesn't support auto prefixing for custom routes, it makes the module almost obsolete for such applications.

**Comment by MuhammadM1998** [comment]
Thanks for the great effort🙏 I'd suggest flattening the modules & vue-i18n configs as it's confusing. Abstracting vue-i18n config and exposing relevant options to the module's config would be a better imo

**Comment by kazupon** [comment]
@MuhammadM1998 
Thanks comment!

As mentioned [here](https://github.com/nuxt-modules/i18n/issues/1985), the config flattening of nuxt-i18n and vue-i18n is on this roadmap. However, that's a rather disruptive change. So we may postpone it to the next major version as we have to prioritise nuxt4.

**Comment by NordsKingArt** [comment]
@kazupon are you going to ignore the comment by @MinecraftStorage1? I think it quite makes sense adding support for custom routes. I thought even if there is no support for auto prefixing, maybe you will make it possible to use composables like useLocalePath or useSwitchLocalePath? Right now only limited functionalities are available for custom routing.

**Comment by BobbieGoede** [comment]
@MinecraftStorage1 @NordsKingArt 
Please open a separate issue describing this feature (or add details to an issue specific to it if it already exists).

The changes in v9 are mostly focused on deprecating and removing old features and updating dependencies to their next majors (e.g. Nuxt 4, Vue I18n v10) since these usually introduce breaking changes.

**Comment by BobbieGoede** [comment]
I think I will postpone the flattening/merging of nuxt-i18n and vue-i18n for a later major version, I don't have a clear approach on how to do this and there's larger structural changes I would like to make that could make it easier.

The main priorities will be supporting Nuxt 4 and smaller (long-standing) breaking changes.

**Comment by kazupon** [comment]
@BobbieGoede 
I agree.
I don't have a good idea for config flat, so let's postpone that and focus on Nuxt4 support first!

**Comment by BobbieGoede** [comment]
I think we can publish a first release candidate soon, and if all goes well, I estimate we'll have a stable release somewhere in October 💪

**Comment by kazupon** [comment]
Well done!

I'm currently a bit busy with preparations for Vue Fes Japan, so I'll leave the release to you!
It will be your first experience of releasing a major release!

**Comment by BobbieGoede** [comment]
Closing this as we have made the breaking changes needed and published the [first release candidate](https://github.com/nuxt-modules/i18n/releases/tag/v9.0.0-rc.1). (This release has an issue for projects using `npm` https://github.com/nuxt-modules/i18n/issues/3152)

I have opened an issue (https://github.com/nuxt-modules/i18n/issues/3163) to track one of the possible changes I originally wanted to make for v9, but I believe it can be made in a non-breaking way so it can still be implemented during v9's development.

I hope the typescript improvements should attract more users to try out the release candidate, feedback is all we need to determine v9's stability and whether it's time for a stable major release 💪
